//! Formatting invariants of a `.svelte.(js|ts)` module.

use rsvelte_core::compiler::ModuleCompileOptions;
use rsvelte_core::{GenerateMode, compile_module};

fn client(src: &str) -> String {
    compile_module(
        src,
        ModuleCompileOptions {
            filename: Some("store.svelte.js".to_string()),
            generate: GenerateMode::Client,
            dev: false,
            ..Default::default()
        },
    )
    .expect("compile")
    .js
    .code
}

const CLASS: &str = "export class R {\n\t#x = $state({});\n\n\tconstructor(s) {\n\t\tconst b = 2;\n\t\tthis.#x = s;\n\t}\n\n\tm(s) {\n\t\tconst a = 1;\n\t\treturn this.#x;\n\t}\n}\n";

/// The header is prepended to the printed program, not carried as a statement:
/// a comment-only statement parses to nothing, leaving the comment to flush at
/// the body tail.
#[test]
fn the_generated_by_header_leads_the_file() {
    let out = client(CLASS);
    assert!(
        out.starts_with("/* store.svelte.js generated by Svelte v"),
        "header must lead the file:\n{out}"
    );
    assert_eq!(
        out.matches("generated by Svelte v").count(),
        1,
        "header emitted more than once:\n{out}"
    );
}

/// The printer normalizes a source blank line between adjacent declarations.
#[test]
fn same_kind_single_line_statements_get_no_margin() {
    let src = "export function f() {\n\tconst a = 1;\n\n\tconst b = 2;\n\n\treturn a + b;\n}\n";
    let out = client(src);
    assert!(
        out.contains("\tconst a = 1;\n\tconst b = 2;\n"),
        "adjacent single-line consts must not keep a margin:\n{out}"
    );
}
